# -*- coding: utf-8 -*-
"""e3_franco_rosales_e1_s7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13PF-KaACcV6WJ1CODZw3b5MVbNr6uVzA
"""

import random as rd
import numpy as np

matriz = np.zeros((3,3), dtype=int)
for i in range (3):
  for j in range (3):
    matriz[i,j]=rd.randint(1,100)

print(matriz)
print(f'promedio de los elementos: {np.mean(matriz)}')
print(f'suma de los elementos: {np.sum(matriz)}')
print(f'elemento mayor: {np.max(matriz)}')
print(f'elemento menor: {np.min(matriz)}')
print(f'elementos de la diagonal principal: {np.diag(matriz)}')